### ISSUE TITLE
Question about 16K image example

### ISSUE THREAD

**Issue by zhuole1025** [Huage001/LinFusion#1]
Thanks for your great work! I wonder how to generate a 16k image using this proposed model, which is trained on 512 images. Do you use techniques like multidiffusion or using 16K images for finetuning?

**Comment by Huage001** [comment]
Thanks for your interest! In our current experiments, we generate 1024-resolution image first and gradually upscale the image using [SDEdit](https://huggingface.co/docs/diffusers/en/api/pipelines/stable_diffusion/img2img). We will update the corresponding codes soon.

Moreover, it is feasible to use LinFusion together with works like multidiffusion for dedicated high-resolution generation. You could just add the two lines of codes shown in README.

**Comment by Huage001** [comment]
> Thanks for your interest! In our current experiments, we generate 1024-resolution image first and gradually upscale the image using [SDEdit](https://huggingface.co/docs/diffusers/en/api/pipelines/stable_diffusion/img2img). We will update the corresponding codes soon.
> 
> Moreover, it is feasible to use LinFusion together with works like multidiffusion for dedicated high-resolution generation. You could just add the two lines of codes shown in README.

The corresponding codes are updated [here](https://github.com/Huage001/LinFusion/blob/main/examples/ultra_text2image_w_sdedit.ipynb).

**Comment by FNsi** [comment]
Emmm. Whats the expected difference between 16k finetunes and that img2img method? I knew it's hard to find a decent dataset with 16k images anyway...

**Comment by Huage001** [comment]
> Emmm. Whats the expected difference between 16k finetunes and that img2img method? I knew it's hard to find a decent dataset with 16k images anyway...

If we could find a dataset with 16k-resolution images and have the computational resources to support training, it would be perfect, and the resultant model would support text-to-16k image generation directly. However, it is extremely hard.

Thus, we have to find ways to make models trained under lower resolutions capable for higher resolution generation. Img2Img is one of these ways. And we are actively exploring other ways and will update this repo if there is any progress.

**Comment by WHUEugene** [comment]
> Emmm. Whats the expected difference between 16k finetunes and that img2img method? I knew it's hard to find a decent dataset with 16k images anyway...

I have an amazing 12K image dataset in the field of remote sensing , i'm wondering if we can work together

**Comment by FNsi** [comment]
> > Emmm. Whats the expected difference between 16k finetunes and that img2img method? I knew it's hard to find a decent dataset with 16k images anyway...
> 
> 
> 
> I have an amazing 12K image dataset in the field of remote sensing , i'm wondering if we can work together
> 
> 

Should ask the owner man😂

**Comment by Huage001** [comment]
> > Emmm. Whats the expected difference between 16k finetunes and that img2img method? I knew it's hard to find a decent dataset with 16k images anyway...
> 
> I have an amazing 12K image dataset in the field of remote sensing , i'm wondering if we can work together

Sure, we are opening for collaboration. Just drop me an email~
