### ISSUE TITLE
Discussion : Eager for the training code 🤗 

### ISSUE THREAD

**Issue by alielfilali01** [Huage001/LinFusion#4]
Interesting work with huge promises 🔥 Congrats 🤗 .
Personally i'm eagerly waiting for the training code and see how i can tweak it to train a LinFusion based on arabic text !

**Comment by Yuanshi9815** [comment]
Thank you for your interest and kind words! We are currently optimizing our training code and will notify you as soon as it's released. Looking forward to your innovative application with Arabic text!

**Comment by Huage001** [comment]
> Interesting work with huge promises 🔥 Congrats 🤗 . Personally i'm eagerly waiting for the training code and see how i can tweak it to train a LinFusion based on arabic text !

Hi, we are glad to release the training code at `src/train/distill.py` and the script at `examples/train/distill.sh`. Looking forward to your exploration on Arabic text!

**Comment by alielfilali01** [comment]
Thank you so much and looking forward to it !
